[package]
name = "resonara-freeverb-editor"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/resonara-freeverb"
[dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "7136831fd071cdd38260d256b0768f080b14a73e", default-features = false, features = ["std"] }
[workspace]
[profile.dev]
debug = 0
[profile.test]
debug = 0
