[package]
name = "resonara-freeverb-editor"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/resonara-freeverb"
[dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "ce807d0f2dfc978c60d7f3b807026455ee101da4", default-features = false, features = ["std"] }
[workspace]
[profile.dev]
debug = 0
[profile.test]
debug = 0
