[package]
name = "resonara-freeverb-editor"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/petitstrawberry/resonara-freeverb"
[dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "6dbc9d87563d7d1dba529f04e7fbdfc850ca6ab6", default-features = false, features = ["std"] }
[workspace]
[profile.dev]
debug = 0
[profile.test]
debug = 0
